### ISSUE TITLE
Why was `argInt` removed? 

### ISSUE THREAD

**Issue by MangoIV** [remiturk/libffi#13]
`argInt` was removed as a breaking change in the version bump `0.1 -> 0.2`, but there was no note in the changelog on what it was replaced with/ why it was removed, can you please clarify on that? 

Thanks in advance.

**Comment by RyanGlScott** [comment]
My apologies for not noticing a7d4f9af169302f889b3b8e62f37bd488e517bbd before writing the `0.2` changelog entry.

While I wasn't the one who wrote this commit, I can make an educated guess behind its intent. The size of an `Int` or `Word` in Haskell is not necessarily the same size as an `int` or `unsigned int` in C, respectively, which makes it easy to mix up the two. For instance, an `Int` is 8 bytes on a 64-bit Linux GHC, but an `int` is 4 bytes on a 64-bit Linux GCC. This could lead to confusing behavior at runtime if a user supplied an `Int` value that could not fit into the size of an `int`.

For these reasons, I think the right thing to do is to avoid the use of `arg{Int,Word}` and `ret{Int,Word}` and instead use functions that precisely specify the size of the argument on the C side. (e.g., if your function takes an integer argument 4 bytes large, use `argInt32`.) Unfortunately, I made a `0.2` Hackage release before we could introduce a proper deprecation cycle, so perhaps the best thing to do is to retroactively adjust the changelog to mention this.

**Comment by RyanGlScott** [comment]
I've retroactively added the rationale for this change to the changelog in dd4c54aa8f417aa436d1ac795ec647fe8fe05fd8. Is this a satisfactory resolution, @MangoIV? If you'd like, I could upload a new minor release of `libffi` to Hackage with these changes so that the changelog on Hackage displays these changes.

**Comment by MangoIV** [comment]
Thank you, yes, this is enough information. I don't care for the new hackage upload, as I have my clarification but I guess it would be helpful for other, I guess this remains your decision. Thank you for resolving this so quickly!
